# Generated by Django 5.2.3 on 2025-07-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.CharField(help_text='Unique ID from OPIS data', max_length=50, unique=True)),
                ('truckstop_name', models.CharField(blank=True, help_text='Name of the truckstop', max_length=255, null=True)),
                ('address', models.CharField(blank=True, help_text='Physical street address', max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('rack_id', models.CharField(blank=True, help_text='Rack ID from OPIS data', max_length=50, null=True)),
                ('retail_price', models.FloatField(help_text='Fuel price per gallon')),
                ('latitude', models.FloatField(blank=True, help_text='Geocoded latitude', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Geocoded longitude', null=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
            },
        ),
    ]
