# Generated by Django 5.2.3 on 2025-07-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimizer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_truckstop_id',
            field=models.CharField(help_text='Unique ID from OPIS data', max_length=50),
        ),
    ]
